services:
  ros2:
    container_name: ros2_container
    build:
      context: ros
      dockerfile: Dockerfile
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - ROS_VERSION=2
      - ROS_DISTRO=jazzy
      - ROS_PYTHON_VERSION=3

      - AWS_ACCESS_KEY_ID=''
      - AWS_SECRET_ACCESS_KEY=''
      - AWS_DEFAULT_REGION=ap-south-1
      - AWS_REGION=ap-south-1

      - PORT=8883
      - THING_NAME=rover_iot_thing
      - IOT_POLICY_NAME=_policy
      - THING_GROUP_NAME=ros_thing_group

      - IOT_CONFIG_TEMPLATE=/home/ros/templates/iot_config_template.json
      - IOT_POLICY_TEMPLATE=/home/ros/templates/iot_policy_template.json

      - CERT_FOLDER_LOCATION=/home/ros/cert/
      - IOT_CONFIG_FILE=/home/ros/cert/iot_config.json
      - IOT_POLICY_FILE=/home/ros/cert/iot_policy.json

      - KVS_SDK_ROOT_FOLDER=/home/ros/kvs/
      - IAM_KVS_ROLE_NAME=iot_kvs_role
      - IAM_KVS_POLICY_NAME=iot_kvs_policy
      - IAM_KVS_WEBRTC_POLICY_NAME=iot_kvs_webrtc_policy
      - IOT_KVS_ROLE_ALIAS=iot_kvs_role_alias
      - IOT_KVS_POLICY_NAME=iot_kvs_webrtc_policy

      - IAM_KVS_ROLE_POLICY_TEMPLATE=/home/ros/templates/iam_role_policy_template.json
      - IAM_KVS_POLICY_TEMPLATE=/home/ros/templates/iam_kvs_policy_template.json
      - IAM_KVS_WEBRTC_POLICY_TEMPLATE=/home/ros/templates/iam_kvs_webrtc_policy_template.json
      - IOT_KVS_POLICY_TEMPLATE=/home/ros/templates/iot_kvs_policy_template.json

      - IAM_KVS_CONFIG_FILE=/home/ros/cert/iam_policy.json
      - IOT_KVS_ROLE_ALIAS_CONFIG_FILE=/home/ros/cert/iam_role_alias.json
      - IOT_KVS_POLICY_FILE=/home/ros/cert/iot_kvs_policy.json
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./.aws:/root/.aws
      - ./ros:/home/ros
    network_mode: host
    tty: true
    stdin_open: true
    # devices:
    # - /dev/video0:/dev/video0
    ports:
      - "8883:8883"
    entrypoint: ["bash"]

  # frontend:
  #   container_name: frontend_container
  #   build:
  #     context: frontend
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8080:8080"
